apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 890742601773.dkr.ecr.us-east-1.amazonaws.com/devops-nodejs-app:${IMAGE_TAG}
          ports:
            - containerPort: 3000
